### PR TITLE
Modernize icon and update project settings to work with Xcode 10

### PR DESCRIPTION
**Pull request by uvesten**
Hi there! 

I recently switched from Chrome to Firefox, and I make haeavy use of multiple profiles. Was a bit surprised that this (old) program seemed to be the way to do it on macOS, but it works very well! 

I was just a bit bothered by the old-style icon and the fact that I did not know how long the app would keep working, so I decided to look at the source. 

In short: I updated the icon, updated the project settings to current recommended for a macOS app, and fixed the few compiler warnings there were.

### CODE REVIEW

**Comment by themartorana** [comment]
Hi Petter! This is great, thank you. I know people still use this but it has languished over the past few Xcode updates.

Regarding the icon, the other MFF icon was an open-source icon. I don't know how the Firefox icon you imported is licensed. It needs to be compatible with the MIT license MFF uses - that is, it can't be GPL.

Do you know how it's licensed?

Thanks!

**Comment by uvesten** [comment]
Looking into it, and so far I've found this: https://design.firefox.com/photon/visuals/product-identity-assets.html 

So, the svg icons are CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0/), which should be good. 

I'll make a new .icns-file from the svg, using inkscape to convert, and then iconutil to bundle (see https://graphicdesign.stackexchange.com/questions/90674/macos-icons-combining-three-different-designs-into-one-icns-file), and add something to the credits about the icon. 

I'll drop mozilla an email and ask too. Just to check that I've interpreted their rules correctly. 

When that's done, I'll update the pull request!

**Comment by themartorana** [comment]
Thanks so much for this!

**Comment by uvesten** [comment]
Thanks for the app :) 

Still waiting to hear back from mozilla, but I guess using the icon should be fine. I'll ping when I hear something.

**Comment by themartorana** [comment]
Yeah, I thought you met the requirements of the CC license with credit, so if you don't hear back, I think we're still in compliance.

**Pull request merged**
